apiVersion: asm.alauda.io/v1beta2
kind: CaseMonitor
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: componenthealthcheck
  namespace: {{ $.Release.Namespace }}
spec:
  interval: "60"
  namespaceSelector:
    matchNames:
    - istio-system
    - {{ $.Release.Namespace }}
  crds:
    - name: prometheus
      group: asm.alauda.io
      kind: ClusterConfig
      version: v1beta1
      crdname: asm-cluster-config
      namespace: ""
      operator: HttpPing
      url: prometheusURL
      customErrors:
      - "PrometheusURLErr"
      - "PrometheusRunningErr"
    - name: elasticsearch
      group: asm.alauda.io
      kind: ClusterConfig
      version: v1beta1
      crdname: asm-cluster-config
      namespace: ""
      operator: HttpPing
      url: elasticsearch.url
      basicAuth:
        username: elasticsearch.username
        password: elasticsearch.password
      customErrors:
      - "ElasticsearchURLErr"
      - "ElasticsearchRunningErr"
  selector:
    matchLabels:
      asm.{{ .Values.global.labelBaseDomain }}/healthcheck-component: "true"