apiVersion: asm.alauda.io/v1beta2
kind: CaseMonitor
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: monitoringservice
  namespace: {{ $.Release.Namespace }}
spec:
  interval: "60"
  namespaceSelector:
    matchNames:
    - istio-system
    - {{ $.Release.Namespace }}
  crds:
    - name: prometheus
      group: asm.alauda.io
      kind: ClusterConfig
      version: v1beta1
      crdname: asm-cluster-config
      namespace: ""
      operator: HttpPing
      url: prometheusURL
      customErrors:
      - "PrometheusURLErr"
      - "PrometheusRunningErr"
    - name: serviceMonitor
      group: monitoring.coreos.com
      kind: ServiceMonitor
      version: v1
      crdname: istio-monitor
      namespace: "istio-system"
      operator: Exists
      customErrors:
      - "ServiceMonitorNotAvailable"
      - "PrometheusOperatorNotInstall"
  selector:
    matchLabels:
      asm.{{ .Values.global.labelBaseDomain }}/healthcheck-monitoring: "true"