apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: outlierdetections.asm.alauda.io
spec:
  conversion:
    strategy: None
  group: asm.alauda.io
  names:
    kind: OutlierDetection
    listKind: OutlierDetectionList
    plural: outlierdetections
    shortNames:
      - od
    singular: outlierdetection
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST chart this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              properties:
                baseEjectionTime:
                  type: string
                consecutiveErrors:
                  format: int32
                  type: integer
                host:
                  type: string
                interval:
                  type: string
                maxEjectionPercent:
                  format: int32
                  type: integer
              type: object
            status:
              type: object
      served: true
      storage: true
status:
  acceptedNames:
    kind: OutlierDetection
    listKind: OutlierDetectionList
    plural: outlierdetections
    shortNames:
      - od
    singular: outlierdetection
  conditions:
    - lastTransitionTime: "2020-12-16T09:34:29Z"
      message: 'spec.validation.openAPIV3Schema.type: Required value: must not be empty
      at the root'
      reason: Violations
      status: "True"
      type: NonStructuralSchema
    - lastTransitionTime: "2020-12-16T09:34:29Z"
      message: no conflicts found
      reason: NoConflicts
      status: "True"
      type: NamesAccepted
    - lastTransitionTime: "2020-12-16T09:34:29Z"
      message: the initial names have been accepted
      reason: InitialNamesAccepted
      status: "True"
      type: Established
  storedVersions:
    - v1alpha1