apiVersion: asm.alauda.io/v1beta1
kind: ClusterConfig
metadata:
    name: asm-cluster-config
    labels:
        heritage: {{ $.Release.Service }}
        release: {{ $.Release.Name }}
spec:
    jaegercollector:
        image: {{ .Values.global.registry.address  }}/{{ .Values.global.images.jaeger_collector.repository  }}:{{ .Values.global.images.jaeger_collector.tag  }}
    elasticsearch:
        url: {{ .Values.jaeger.elasticsearch.serverurl  }}
{{ if .Values.jaeger.elasticsearch.username }}
        username: {{ .Values.jaeger.elasticsearch.username  }}
{{ else }}
        username: ""
{{ end }}
{{ if .Values.jaeger.elasticsearch.password }}
        password: {{ .Values.jaeger.elasticsearch.password  }}
{{ else }}
        password: ""
{{ end }}
    forbiddenSidecarInjectNamespaces:
    - {{ .Values.istio.namespace }}
    hiddenServiceNamesInTracing:
    - {{ .Values.jaeger.nsZipkinCollector.host }}
    pilot:
        tracesampling: {{ .Values.istio.traceSampling }}
    ingressgateway:
        nodeport: {{ .Values.istio.gatewayNodeportValue }}
        httpsNodeport: {{ .Values.istio.gatewayHttpsNodeportValue }}
    ipranges:
        mode: include
        ranges:
        {{ range $iprange := split "," .Values.istio.includeIPRanges }}
        - "{{ $iprange }}"
        {{ end }}
    jaegerURL: "{{ .Values.jaeger.url }}"
    grafanaURL: "{{ .Values.grafana.url }}"
    prometheusURL: "{{ .Values.prometheus.url }}"
