apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: servicemesh-controller:extension-apiserver-authentication-reader
  namespace: {{ $.Release.Namespace }}
  labels:
    heritage: {{ $.Release.Service }}
    release: {{ $.Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: servicemesh-controller
  namespace: {{ $.Release.Namespace }}