apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: asm-controller-webhook
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: asm-controller-webhook
      namespace: {{ $.Release.Namespace }}
      path: /webhook/validate/virtualservices
  admissionReviewVersions:
  - v1beta1
  failurePolicy: Fail
  name: vvirtualservices.kb.io
  objectSelector:
    matchLabels:
      asm.{{ .Values.global.labelBaseDomain }}/vstype: root
  rules:
  - apiGroups:
    - networking.istio.io
    apiVersions:
    - v1alpha3
    operations:
    - CREATE
    - UPDATE
    resources:
    - virtualservices
  sideEffects: None
