apiVersion: v1
kind: Service
metadata:
  name: zipkin
  namespace: {{ .Values.istio.namespace }}
  labels:
    app: jaeger
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.jaeger.zipkinService.type }}
  ports:
    - port: {{ .Values.jaeger.zipkinService.externalPort }}
      targetPort: {{ .Values.jaeger.zipkinService.internalPort }}
      protocol: TCP
      name: {{ .Values.jaeger.zipkinService.portName }}
  selector:
    app: jaeger
    app.kubernetes.io/component: collector
    app.kubernetes.io/part-of: jaeger
