apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: canarytemplates.asm.alauda.io
spec:
  group: asm.alauda.io
  version: v1alpha1
  versions:
    - name: v1alpha1
      served: true
      storage: true
  names:
    plural: canarytemplates
    singular: canarytemplate
    kind: CanaryTemplate
    categories:
      - all
  scope: Namespaced
  subresources:
    status: {}
  additionalPrinterColumns:
    - name: Interval
      type: string
      JSONPath: .spec.analysis.interval
      priority: 1
    - name: Mirror
      type: boolean
      JSONPath: .spec.analysis.mirror
      priority: 1
    - name: StepWeight
      type: string
      JSONPath: .spec.analysis.stepWeight
      priority: 1
    - name: MaxWeight
      type: string
      JSONPath: .spec.analysis.maxWeight
      priority: 1
  validation:
    openAPIV3Schema:
      properties:
        spec:
          required:
            - analysis
          properties:
            skipAnalysis:
              description: Skip analysis and promote canary
              type: boolean
            analysis:
              description: Canary analysis for this canary
              type: object
              oneOf:
                - required: ["interval", "threshold", "iterations"]
                - required: ["interval", "threshold", "stepWeight"]
              properties:
                interval:
                  description: Schedule interval for this canary
                  type: string
                  pattern: "^[0-9]+(m|s)"
                iterations:
                  description: Number of checks to run for A/B Testing and Blue/Green
                  type: integer
                threshold:
                  description: Max number of failed checks before rollback
                  type: integer
                maxWeight:
                  description: Max traffic percentage routed to canary
                  type: integer
                stepWeight:
                  description: Incremental traffic percentage step
                  type: integer
                mirror:
                  description: Mirror traffic to canary
                  type: boolean
                match:
                  description: A/B testing match conditions
                  type: array
                  items:
                    type: object
                    properties:
                      headers:
                        type: object
                        additionalProperties:
                          oneOf:
                            - required: ["exact"]
                            - required: ["prefix"]
                            - required: ["suffix"]
                            - required: ["regex"]
                          type: object
                          properties:
                            exact:
                              format: string
                              type: string
                            prefix:
                              format: string
                              type: string
                            suffix:
                              format: string
                              type: string
                            regex:
                              format: string
                              type: string
                metrics:
                  description: Metric check list for this canary
                  type: array
                  items:
                    type: object
                    required: ["name"]
                    properties:
                      name:
                        description: Name of the metric
                        type: string
                      interval:
                        description: Interval of the query
                        type: string
                        pattern: "^[0-9]+(m|s)"
                      threshold:
                        description: Max value accepted for this metric
                        type: number
                      thresholdRange:
                        description: Range accepted for this metric
                        type: object
                        properties:
                          min:
                            description: Min value accepted for this metric
                            type: number
                          max:
                            description: Max value accepted for this metric
                            type: number
                      query:
                        description: Prometheus query
                        type: string
                      templateRef:
                        description: Metric template reference
                        type: object
                        required: ["name"]
                        properties:
                          name:
                            description: Name of this metric template
                            type: string
                          namespace:
                            description: Namespace of this metric template
                            type: string
                webhooks:
                  description: Webhook list for this canary
                  type: array
                  items:
                    type: object
                    required: ["name", "url"]
                    properties:
                      name:
                        description: Name of the webhook
                        type: string
                      type:
                        description: Type of the webhook pre, post or during rollout
                        type: string
                        enum:
                          - ""
                          - confirm-rollout
                          - pre-rollout
                          - rollout
                          - confirm-promotion
                          - post-rollout
                          - event
                          - rollback
                      url:
                        description: URL address of this webhook
                        type: string
                        format: url
                      timeout:
                        description: Request timeout for this webhook
                        type: string
                        pattern: "^[0-9]+(m|s)"
                      metadata:
                        description: Metadata (key-value pairs) for this webhook
                        type: object
                        additionalProperties:
                          type: string