apiVersion: asm.alauda.io/v1beta2
kind: CaseMonitor
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: sidecarinjection
  namespace: {{ $.Release.Namespace }}
spec:
  interval: "60"
  namespaceSelector:
    matchNames:
    - istio-system
  pingurls: []
  selector:
    matchLabels:
      asm.{{ .Values.global.labelBaseDomain }}/healthcheck-sidecarinjection: "true"