apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: sidecar-monitor
  namespace: {{ .Values.istio.namespace }}
  labels:
    heritage: {{ $.Release.Service }}
    release: {{ $.Release.Name }}
    monitoring: pods
    prometheus: kube-prometheus
spec:
  selector:
    matchExpressions:
      - key: service.istio.io/canonical-name
        operator: Exists
  namespaceSelector:
    any: true
  jobLabel: service.istio.io/canonical-name
  podMetricsEndpoints:
    - targetPort: 15090
      interval: 5s
      path: /stats/prometheus
