
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: clusterconfigs.asm.alauda.io
spec:
  group: asm.alauda.io
  names:
    kind: ClusterConfig
    listKind: ClusterConfigList
    plural: clusterconfigs
    singular: clusterconfig
  scope: ""
  validation:
    openAPIV3Schema:
      description: ClusterConfig is the Schema for the clusterconfigs API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ClusterConfigSpec defines the desired state of ClusterConfig
          properties:
            elasticsearch:
              properties:
                password:
                  type: string
                url:
                  type: string
                username:
                  type: string
              required:
              - url
              type: object
            forbiddenSidecarInjectNamespaces:
              items:
                type: string
              type: array
            grafanaURL:
              type: string
            hiddenServiceNamesInTracing:
              items:
                type: string
              type: array
            ipranges:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "make" to regenerate code after modifying this file'
              properties:
                mode:
                  type: string
                ranges:
                  items:
                    type: string
                  type: array
              required:
              - mode
              - ranges
              type: object
            jaegerURL:
              type: string
            prometheusURL:
              type: string
          type: object
        status:
          description: ClusterConfigStatus defines the observed state of ClusterConfig
          type: object
      type: object
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
