
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: connectionpools.asm.alauda.io
spec:
  group: asm.alauda.io
  names:
    kind: ConnectionPool
    listKind: ConnectionPoolList
    plural: connectionpools
    singular: connectionpool
  scope: ""
  validation:
    openAPIV3Schema:
      description: ConnectionPool is the Schema for the connectionpools API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ConnectionPoolSpec defines the desired state of ConnectionPool
          properties:
            host:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "make" to regenerate code after modifying this file'
              type: string
            http:
              description: Settings applicable to HTTP1.1/HTTP2/GRPC connections.
              properties:
                httpMaxPendingRequests:
                  description: Maximum number of pending HTTP1 requests to a destination.
                    Default 1024.
                  format: int32
                  type: integer
                httpMaxRequests:
                  description: Maximum number of HTTP2 requests to a backend. Default
                    1024.
                  format: int32
                  type: integer
                maxRequestsPerConnection:
                  description: parameter 1 disables keep alive. Default 0, meaning
                    "unlimited",
                  format: int32
                  type: integer
                maxRetries:
                  description: cluster at a given time. Defaults to 3.
                  format: int32
                  type: integer
              type: object
            tcp:
              properties:
                connectTimeout:
                  description: TCP connection timeout.
                  type: string
                maxConnections:
                  description: Maximum number of HTTP1 /TCP connections to a destination
                    host. Default 1024.
                  format: int32
                  type: integer
              type: object
          type: object
        status:
          description: ConnectionPoolStatus defines the observed state of ConnectionPool
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
