
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: casemonitors.asm.alauda.io
spec:
  group: asm.alauda.io
  names:
    kind: CaseMonitor
    listKind: CaseMonitorList
    plural: casemonitors
    singular: casemonitor
  scope: ""
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: false
  - name: v1beta2
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
