
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: alertproviders.flagger.app
spec:
  group: flagger.app
  names:
    kind: AlertProvider
    listKind: AlertProviderList
    plural: alertproviders
    singular: alertprovider
  scope: ""
  validation:
    openAPIV3Schema:
      description: AlertProvider is the configuration of alerting for a specific provider
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: AlertProviderSpec is the specification of the desired behavior
            of the AlertProvider
          properties:
            address:
              description: HTTP(S) webhook address of this provider
              type: string
            channel:
              description: Alert channel for this provider
              type: string
            secretRef:
              description: Secret reference containing the provider webhook URL
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            type:
              description: Type of provider
              type: string
            username:
              description: Bot username for this provider
              type: string
          required:
          - type
          type: object
        status:
          properties:
            conditions:
              description: Conditions of this status
              items:
                properties:
                  lastTransitionTime:
                    description: LastTransitionTime of this condition
                    format: date-time
                    type: string
                  lastUpdateTime:
                    description: LastUpdateTime of this condition
                    format: date-time
                    type: string
                  message:
                    description: Message associated with this condition
                    type: string
                  reason:
                    description: Reason for the current status of this condition
                    type: string
                  status:
                    description: Status of this condition
                    type: string
                  type:
                    description: Type of this condition
                    type: string
                required:
                - status
                - type
                type: object
              type: array
          type: object
      required:
      - spec
      - status
      type: object
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
