
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: asms.operator.alauda.io
spec:
  group: operator.alauda.io
  names:
    kind: Asm
    listKind: AsmList
    plural: asms
    singular: asm
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Asm is the Schema for the asms API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: AsmSpec defines the desired state of Asm
          properties:
            parameters:
              type: string
          type: object
        status:
          description: AsmStatus defines the observed state of Asm
          properties:
            deleteConditions:
              additionalProperties:
                items:
                  properties:
                    lastTransitionTime:
                      format: date-time
                      type: string
                    message:
                      type: string
                    name:
                      type: string
                    observedGeneration:
                      format: int64
                      type: integer
                    reason:
                      type: string
                    status:
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - name
                  - reason
                  - status
                  type: object
                type: array
              type: object
            installConditions:
              additionalProperties:
                items:
                  properties:
                    lastTransitionTime:
                      format: date-time
                      type: string
                    message:
                      type: string
                    name:
                      type: string
                    observedGeneration:
                      format: int64
                      type: integer
                    reason:
                      type: string
                    status:
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - name
                  - reason
                  - status
                  type: object
                type: array
              type: object
            state:
              type: string
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
